[uwsgi]
callable = app

manage-script-name = true

master = true
processes = 2

socket = thesaurusx.sock
chmod-socket = 660
vacuum = true

die-on-term = true
 
; Sub-path mounting — the app will be served at /stylethesaurus
mount = /stylethesaurus=wsgi.py
manage-script-name = true
